- locale: en-US
  path:   default
  label:  English

- locale: fr-FR
  path:   fr
  label:  Français

- locale: zh-CN
  path:   cn
  label:  简体中文

- locale: hu-HU
  path:   hu
  label:  Magyar

- locale: es-ES
  path:   es
  label:  Español

- locale: de-DE
  path:   de
  label:  Deutsch

