language: node_js
node_js:
  - '8'

dist:     trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

cache:
  yarn: true
  directories:
    - node_modules

# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - make install

script:
  - make fmt_check
  - make lint
  # too many errors, should be fixed or rules updated
  #- yarn lint
  # ensure the project builds correctly
  #- yarn build
  # starts static server
  #- cd public && python -m SimpleHTTPServer &
  #- sleep 6
  # ensure the capture works (because it relies on selectors)
  #- cd cli && ./cli capture
