- id: home
  path: /
  type: page
  is_hidden: true

- id: demographics
  path: /demographics
  type: page
  blocks:
      - participation-by-country
      - gender-breakdown
      - salaries
      - salary-per-country
      - years-of-experience
      - company-size

- id: features
  path: /features
  type: page
  children:
      - id: layout
        path: /layout
        type: features
        data:
            section: layout
        blocks:
            - overview
            - css-grid
            - flexbox
            - css-multi-column
            - css-writing-modes
            - css-exclusions
            - conclusion
        # children:
        #     - id: layout-results
        #       path: /results
        #       type: features_results
        #       data:
        #           section: layout
        #       blocks:
        #           - css-grid
        #           - flexbox
        #           - css-multi-column
        #           - css-writing-modes
        #           - css-exclusions
        #     - id: layout-conclusion
        #       path: /conclusion
        #       type: features_conclusion
        #       data:
        #           section: layout

      - id: shapes-and-graphics
        path: /shapes-and-graphics
        type: features_intro
        data:
            section: shapes-and-graphics
        blocks:
            - overview
        children:
            - id: shapes-and-graphics-results
              path: /results
              type: features_results
              data:
                  section: shapes-and-graphics
              blocks:
                  - css-shapes
                  - object-fit
                  - clip-path
                  - css-masks
                  - blend-modes
                  - css-filter-effects
            - id: shapes-and-graphics-conclusion
              path: /conclusion
              type: features_conclusion
              data:
                  section: shapes-and-graphics

      - id: interactions
        path: /interactions
        type: features_intro
        data:
            section: interactions
        blocks:
            - overview
        children:
            - id: interactions-results
              path: /results
              type: features_results
              data:
                  section: interactions
              blocks:
                  - css-scroll-snap
                  - overscroll-behavior
                  - overflow-anchor
            - id: interactions-conclusion
              path: /conclusion
              type: features_conclusion
              data:
                  section: interactions

      - id: typography
        path: /typography
        type: features_intro
        data:
            section: typography
        blocks:
            - overview
        children:
            - id: typography-results
              path: /results
              type: features_results
              data:
                  section: typography
              blocks:
                  - web-fonts-font-face
                  - variable-fonts
                  - line-breaking-properties
                  - font-variant
                  - initial-letter
            - id: typography-conclusion
              path: /conclusion
              type: features_conclusion
              data:
                  section: typography

      - id: animations-and-transforms
        path: /animations-and-transforms
        type: features_intro
        data:
            section: animations-and-transforms
        blocks:
            - overview
        children:
            - id: animations-and-transforms-results
              path: /results
              type: features_results
              data:
                  section: animations-and-transforms
              blocks:
                  - css-transitions
                  - css-transforms
                  - css-animations
            - id: animations-and-transforms-conclusion
              path: /conclusion
              type: features_conclusion
              data:
                  section: animations-and-transforms

      - id: other-features
        path: /other-features
        type: features_intro
        data:
            section: other-features
        blocks:
            - overview
        children:
            - id: other-features-results
              path: /results
              type: features_results
              data:
                  section: other-features
              blocks:
                  - css-variables
                  - support-queries
                  - css-containment
                  - will-change
                  - calc
            - id: other-features-conclusion
              path: /conclusion
              type: features_conclusion
              data:
                  section: other-features

- id: units-and-selectors
  path: /units-and-selectors
  type: page

- id: tools-and-methodology
  path: /tools-and-methodology
  type: page
  children:
      - id: pre-post-processors
        path: /pre-post-processors
        type: tools
        blocks:
            - sass
            - less
            - postcss
            - stylus

      - id: css-frameworks
        path: /css-frameworks
        type: tools
        blocks:
            - bootstrap
            - materialize-css
            - ant-design
            - semantic-ui
            - bulma
            - foundation
            - uikit
            - tachyons
            - primer
            - tailwind
            - purecss

      - id: methodologies
        path: /methodologies
        type: tools
        blocks: []

      - id: css-in-js
        path: /css-in-js
        type: tools
        blocks: []

      - id: other-tools
        path: /other-tools
        type: tools
        blocks: []

- id: environments
  path: /environments
  type: page

- id: resources
  path: /resources
  type: page

- id: opinions
  path: /opinions
  type: page

- id: conclusion
  path: /conclusion
  type: page

- id: support
  path: /support
  type: page
  is_hidden: true
