- id: home
  path: /
  type: page
  is_hidden: true

- id: demographics
  path: /demographics
  type: page
  blocks:
      - id: participation-by-country
        type: countries
      - id: salaries
        type: vertical-bar
      - id: salary-per-country
        type: countries
      - id: years-of-experience
        type: vertical-bar
      - id: company-size
        type: vertical-bar
      - id: source-breakdown
        type: source-breakdown
      - id: gender-breakdown
        type: gender-breakdown
      - id: job-titles
        type: horizontal-bar
      - id: javascript-proficiency
        type: vertical-bar
      - id: backend-proficiency
        type: vertical-bar

- id: features
  path: /features
  type: page
  defaultChartType: feature
  children:
      - id: layout
        path: /layout
        type: features
        data:
            section: layout
        blocks:
            - id: overview
              type: feature-overview
            - css-grid
            - flexbox
            - css-multi-column
            - css-writing-modes
            - css-exclusions
            - id: conclusion
              type: conclusion

      - id: shapes-and-graphics
        path: /shapes-and-graphics
        type: features
        data:
            section: shapes-and-graphics
        blocks:
            - id: overview
              type: feature-overview
            - css-shapes
            - object-fit
            - clip-path
            - css-masks
            - blend-modes
            - css-filter-effects
            - id: conclusion
              type: conclusion

      - id: interactions
        path: /interactions
        type: features
        data:
            section: interactions
        blocks:
            - id: overview
              type: feature-overview
            - css-scroll-snap
            - overscroll-behavior
            - overflow-anchor
            - id: conclusion
              type: conclusion

      - id: typography
        path: /typography
        type: features
        data:
            section: typography
        blocks:
            - id: overview
              type: feature-overview
            - web-fonts-font-face
            - variable-fonts
            - line-breaking-properties
            - font-variant
            - initial-letter
            - id: conclusion
              type: conclusion

      - id: animations-and-transforms
        path: /animations-and-transforms
        type: features
        data:
            section: animations-and-transforms
        blocks:
            - id: overview
              type: feature-overview
            - css-transitions
            - css-transforms
            - css-animations
            - id: conclusion
              type: conclusion

      - id: other-features
        path: /other-features
        type: features
        data:
            section: other-features
        blocks:
            - id: overview
              type: feature-overview
            - css-variables
            - support-queries
            - css-containment
            - will-change
            - calc
            - id: conclusion
              type: conclusion

- id: units-and-selectors
  path: /units-and-selectors
  type: page
  defaultChartType: horizontal-bar
  blocks:
      - units
      - pseudo-elements
      - combinators
      - tree-document-structure
      - attributes
      - links-urls
      - interaction
      - form-controls

- id: tools-and-methodology
  path: /tools-and-methodology
  type: page
  defaultChartType: tool
  children:
      - id: pre-post-processors
        path: /pre-post-processors
        type: tools
        blocks:
            - id: overview
              type: tool-overview
            - sass
            - less
            - postcss
            - stylus

      - id: css-frameworks
        path: /css-frameworks
        type: tools
        blocks:
            - id: overview
              type: tool-overview
            - bootstrap
            - materialize-css
            - ant-design
            - semantic-ui
            - bulma
            - foundation
            - uikit
            - tachyons
            - primer
            - tailwind
            - purecss

      - id: methodologies
        path: /methodologies
        type: tools
        blocks:
            - id: overview
              type: tool-overview
            - bem
            - atomic-css
            - oocss
            - smacss
            - it-css

      - id: css-in-js
        path: /css-in-js
        type: tools
        blocks:
            - id: overview
              type: tool-overview
            - styled-components
            - glamor
            - aphrodite
            - jss
            - styled-jsx
            - radium
            - emotion
            - css-modules

      - id: other-tools
        path: /other-tools
        type: page

- id: environments
  path: /environments
  type: page
  blocks:
    - id: browsers
      type: horizontal-bar
    - id: form-factors
      type: horizontal-bar
    - id: print-styles
      type: vertical-bar
    - id: email-styles
      type: vertical-bar

- id: resources
  path: /resources
  type: page
  blocks:
    - id: blogs-magazines
      type: horizontal-bar
    - id: sites-courses
      type: horizontal-bar
    - id: podcasts
      type: horizontal-bar

- id: opinions
  path: /opinions
  type: page
  blocks:
    - id: easy-to-learn
      type: vertical-bar
    - id: evolving-too-slowly
      type: vertical-bar
    - id: utility-classes
      type: vertical-bar
    - id: selector-nesting
      type: vertical-bar
    - id: programming-language
      type: vertical-bar
    - id: enjoy-css
      type: vertical-bar
    - id: missing-features
      type: horizontal-bar

- id: conclusion
  path: /conclusion
  type: page

- id: support
  path: /support
  type: page
  is_hidden: true
