- id: home
  path: /
  type: page
  is_hidden: true

- id: demographics
  path: /demographics
  type: page
  blocks:
      - participation-by-country
      - gender-breakdown
      - salaries
      - salary-per-country
      - years-of-experience
      - company-size
      - job-titles
      - javascript-proficiency
      - backend-proficiency

- id: features
  path: /features
  type: page
  children:
      - id: layout
        path: /layout
        type: features
        data:
            section: layout
        blocks:
            - overview
            - css-grid
            - flexbox
            - css-multi-column
            - css-writing-modes
            - css-exclusions
            - conclusion

      - id: shapes-and-graphics
        path: /shapes-and-graphics
        type: features
        data:
            section: shapes-and-graphics
        blocks:
            - overview
            - css-shapes
            - object-fit
            - clip-path
            - css-masks
            - blend-modes
            - css-filter-effects
            - conclusion

      - id: interactions
        path: /interactions
        type: features
        data:
            section: interactions
        blocks:
            - overview
            - css-scroll-snap
            - overscroll-behavior
            - overflow-anchor
            - conclusion

      - id: typography
        path: /typography
        type: features
        data:
            section: typography
        blocks:
            - overview
            - web-fonts-font-face
            - variable-fonts
            - line-breaking-properties
            - font-variant
            - initial-letter
            - conclusion

      - id: animations-and-transforms
        path: /animations-and-transforms
        type: features
        data:
            section: animations-and-transforms
        blocks:
            - overview
            - css-transitions
            - css-transforms
            - css-animations
            - conclusion

      - id: other-features
        path: /other-features
        type: features
        data:
            section: other-features
        blocks:
            - overview
            - css-variables
            - support-queries
            - css-containment
            - will-change
            - calc
            - conclusion

- id: units-and-selectors
  path: /units-and-selectors
  type: page
  blocks: 
    - units
    - pseudo-elements
    - combinators
    - tree-document-structure
    - attributes
    - links-urls
    - interaction
    - form-controls

- id: tools-and-methodology
  path: /tools-and-methodology
  type: page
  children:
      - id: pre-post-processors
        path: /pre-post-processors
        type: tools
        blocks:
            - sass
            - less
            - postcss
            - stylus

      - id: css-frameworks
        path: /css-frameworks
        type: tools
        blocks:
            - bootstrap
            - materialize-css
            - ant-design
            - semantic-ui
            - bulma
            - foundation
            - uikit
            - tachyons
            - primer
            - tailwind
            - purecss

      - id: methodologies
        path: /methodologies
        type: tools
        blocks: []

      - id: css-in-js
        path: /css-in-js
        type: tools
        blocks: []

      - id: other-tools
        path: /other-tools
        type: tools
        blocks: []

- id: environments
  path: /environments
  type: page

- id: resources
  path: /resources
  type: page

- id: opinions
  path: /opinions
  type: page

- id: conclusion
  path: /conclusion
  type: page

- id: support
  path: /support
  type: page
  is_hidden: true
